[tool.poetry]
name = "python"
version = "0.1.0"
description = "testing"
authors = ["mitra"]

[tool.poetry.dependencies]
python = "^3.8"
pytest = "^7.2.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
